# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sajal Sharma
tagline:             'Data Scientist and Software Engineer.'
# description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'The internet home of Sajal Sharma. Data Scientist. Software Engineer. Amateur Philosopher.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Sajal Sharma
  url:               http://www.sajalsharma.com
  email:             contact@sajalsharma.com

# Custom vars
version:             1.0.0

#Gems
gems:               [jekyll-paginate]
